spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true





#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://customer-service
#          predicates:
#            - Path=/api/v1/customers/**, /api/v1/accounts/**, /api/v1/loans/**, /api/v1/chat/**
#        - id: admin-service
#          uri: lb://admin-service
#          predicates:
#            - Path=/api/v1/admin/**
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/api/v1/notifications/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost